import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/providers/modal-provider";
import { ToasterProvider } from "@/providers/toast-provider";
import { useEffect, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Toko API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 


{

  // const [isMounted, setIsMounted] = useState(false)

  // useEffect(() => {
  //   setIsMounted(true);
  // }, []);

  // if (!isMounted) return null; // Skip rendering until it's mounted
  return (
    <html lang="en">
        <ClerkProvider>
        <ModalProvider/>
        <ToasterProvider/>
        <body className={inter.className}>{children}</body>
        </ClerkProvider>
      </html>
  );
}
